---
title: "World Chess Championship 1972"
author: "Ben Lee"
format: 
  html:
    embed-resources: true
---

```{r}
## install.packages("tidyverse")
## install.packages("lubridate")
## install.packages("tidyr")
## install.packages("dplyr")
## install.packages("janitor")
## install.packages("fuzzyjoin")
## install.packages("tidygraph")
## install.packages("ggraph")
library(readr)
library(tidyverse)
library(lubridate)
library(tidyr)
library(dplyr)
library(rvest)
library(tidygraph)
library(ggraph)
```

```{r}
fisher_spassky_data <- read_csv(here::here("data/WorldChamp1972.csv"))
large_data <- read_csv(here::here("data/1.World_Chess_Champoinship_CSV.csv"))
```

Clean up data set
```{r}
large_clean <- large_data |>
  filter(Round == 1) |>
  select(c(1,3:6), -Round) |>
  separate_wider_delim(Date, ".", names = c("Year", "na"),
                       too_many = "merge") |>
  select(-na) |>
  mutate(Year = parse_number(Year)) |>
  arrange(desc(Year)) 

## look into champion titles
## change names to they are consistent
```

Gather a new data set of only champions
```{r}
url <- "https://www.chess.com/article/view/world-chess-champions"

h <- read_html(url)

tab <- h %>% html_nodes("table")

objs <- tab %>% html_table()

Classical_WC <- objs[[1]]

colnames(Classical_WC) <- Classical_WC[1, ]

Classical_WC_Clean <- Classical_WC[-1, ]        
```

Clean the new data set and join with the old
```{r}
Classical_Clean <- Classical_WC_Clean |> separate_longer_delim(cols = "Years Won",
                                            delim = ",") |>
  mutate(Year = parse_number(`Years Won`)) |>
  select(Player, Year)

Joined_data <- left_join(Classical_Clean,
          large_clean,
          by = "Year",
          relationship = "many-to-many")

Tidy_df <- Joined_data |>
  slice(-c(11, 12, 19, 20, 31, 39, 45:49, 53, 57, 60, 61)) |>
  separate_wider_delim(cols = White,
                       delim = ",",
                       names = c("Player1", "First_name1")) |>
  separate_wider_delim(cols = Black,
                       delim = ",",
                       names = c("Player2", "First_name2")) |>
  select(c(-First_name1, -First_name2)) |>
  pivot_longer(c(Player1, Player2),
               names_to = "player_num",
               values_to = "player") |>
  select(-1,-3)
```


```{r}
network_df <- Tidy_df |>
  group_by(Year) |>
  reframe(test = t(combn(player, 2))) |>
  mutate(vertex1 = test[ ,1],
         vertex2 = test[ ,2]) |>
  dplyr::select(-test)

network_sum <- network_df |> mutate(player_first = if_else(vertex1 > vertex2,
                                           true = vertex2,
                                           false = vertex1),
                     player_second = if_else(vertex1 > vertex2,
                                            true = vertex1,
                                            false = vertex2)) |>
  dplyr::select(-vertex1, -vertex2) |>
  group_by(player_first, player_second) |>
  summarise(n_players = n())
```

Network Plot
```{r}
nodes <- Tidy_df |> 
  distinct(player) |>
  rename(label = player) |>
  mutate(engine = case_when(
    label %in% c("Zukertort" , "Steinitz" , "Chigorin" , "Gunsberg" , "Lasker", "Marshall" , "Tarrasch" , "Schlechter" , "Janowsky" , "Capablanca", "Alekhine" , "Bogoljubow" , "Euwe" , "Botvinnik" , "Bronstein", "Smyslov" , "Tal" , "Petrosian" , "Spassky" , "Fischer", "Kortschnoj", "Karpov", "Kasparov", "Short", "Anand" ) ~ "Before Engine Dominance",
    label %in% c("Kramnik" , "Leko" , "Topalov" , "Gelfand" , "Carlsen", "Karjakin" , "Caruana" , "Nepomniachtchi") ~ "After Engine Dominance",
    .default = "Transition")) |>
  filter(label %in% c(network_sum |> pull(player_first),
                      network_sum |> pull(player_second))) |>
  rowid_to_column("id")

edges <- left_join(network_sum, nodes, by = join_by(player_first == label)) |>
  rename(from = "id") |>
  left_join(nodes, by = join_by(player_second == label)) |>
  rename(to = "id") |>
  ungroup() |>
  dplyr::select(to, from, n_players)

network_obj <- tbl_graph(nodes = nodes, edges = edges, directed = FALSE)

ggraph(network_obj |> mutate(centrality = centrality_degree()),
                            layout = "kk") +
  geom_edge_link(aes(width = n_players), alpha = 0.7, show.legend = FALSE) +
  geom_node_point(aes(colour = engine,
                      size = centrality), show.legend = FALSE) +
  scale_edge_width(range = c(0.5, 3)) +
  geom_node_text(aes(label = label), repel = TRUE)+
  scale_color_manual(values = c("#DC3220",
                                "#005AB5"))
## who is bogolijubow?
```

